import type { Telegraf } from 'telegraf'

const GUIDE_TEXT = [
  `*SPNETGRAM Admin Bot — Guide*`,
  ``,
  `*1. Platform Overview*`,
  `SPNETGRAM Admin Bot is a comprehensive staff management, moderation, and enterprise governance platform.`,
  `It integrates ticket management, case management, moderation actions, investigations, premium subscriptions,`,
  `economy management, KPI tracking, approval workflows, security operations, monitoring, incident management,`,
  `AI operations, analytics, deep linking, real-time dashboards, enterprise governance, and bidirectional`,
  `synchronization with SPNET-ADMIN.`,
  ``,
  `*2. Departments*`,
  `Staff are organized into five department types:`,
  `• *MODERATION* — Content moderation and user discipline. Manage warnings, mutes, bans.`,
  `• *SUPPORT* — User assistance and ticket resolution. Handle /tickets and user inquiries.`,
  `• *INVESTIGATIONS* — Deep-dive investigations and forensics. Evidence collection, timelines.`,
  `• *ENGINEERING* — Technical development, infrastructure, and system operations.`,
  `• *ADMINISTRATION* — Internal governance, compliance, staff management, and operations.`,
  `Each department has a lead, managers, and members. View with /departments.`,
  ``,
  `*3. Roles (Hierarchy)*`,
  `Every staff member has a role defining their authority level:`,
  `• *OWNER* (1000) — Full platform ownership and absolute control over all resources.`,
  `• *SUPER_ADMINISTRATOR* (900) — System-wide administrative access with no restrictions.`,
  `• *CEO* (850) — Chief executive authority over all business operations.`,
  `• *CTO* (800) — Technical leadership and infrastructure authority.`,
  `• *COO* (750) — Operational leadership and team management.`,
  `• *ADMIN* (700) — Administrative oversight across all departments.`,
  `• *DEPARTMENT_HEAD* (600) — Full authority within their assigned department.`,
  `• *MANAGER* (500) — Team management and operational supervision.`,
  `• *SENIOR_STAFF* (400) — Senior operational staff with advanced privileges.`,
  `• *STAFF* (300) — Standard staff member with basic operational access.`,
  `• *HELPER* (100) — Entry-level support with limited access.`,
  `Use /staff to list active staff. Use /grantrole <staffId> <role> to assign.`,
  ``,
  `*4. Permission System*`,
  `Permissions control access to 20+ resources (USERS, STAFF, MODERATION, CASES, TICKETS, SLA,`,
  `AUDIT, INVESTIGATIONS, NOTIFICATIONS, SETTINGS, DEPARTMENTS, PREMIUM, ECONOMY, KPI, APPROVALS,`,
  `SECURITY, MONITORING, INCIDENTS, ANALYTICS, SYNC, DASHBOARD) with 8 actions:`,
  `CREATE, READ, UPDATE, DELETE, APPROVE, REJECT, ASSIGN, ESCALATE.`,
  `Three layers of access control:`,
  `1. *Role-based* — Inherited from role (default permissions).`,
  `2. *Permission overrides* — Explicit grant/revoke per staff member.`,
  `3. *Temporary permissions* — Time-bound access grants (hours).`,
  `Use /grantpermission <staffId> <resource> <action>, /temporaryaccess, /accessaudit.`,
  ``,
  `*5. Premium Examples*`,
  `• /premium — Premium overview and plan summary`,
  `• /plans — List all premium plans and pricing`,
  `• /requestpremium <userId> <planId> — Grant premium subscription to user`,
  `• /mypremium — Check your own premium status`,
  `Premium features include economy bonuses, priority support, exclusive commands, and storage limits.`,
  `Premium lifecycle is tracked via subscription plans with auto-expiry notifications.`,
  `Use API endpoints for full premium plan and subscription management.`,
  ``,
  `*6. Economy*`,
  `Economy is managed via API endpoints. Bot commands for economy operations are not yet available.`,
  `Use the SPNET-ADMIN interface or direct API calls for economy management.`,
  ``,
  `*7. Security Examples*`,
  `• /security — Security summary dashboard`,
  `• /securitylogs — Recent security events (24h)`,
  `• /risk — Risk analysis and scoring for users`,
  `• /fraud — Fraud pattern detection`,
  `• /sessionaudit — User login session history`,
  `Security system tracks login anomalies, multi-device patterns, risk scoring,`,
  `and trust scores. Events are synced bidirectionally with SPNET-ADMIN.`,
  `Device management and security event logging are available via API.`,
  ``,
  `*8. Approvals*`,
  `Approvals are managed via API endpoints. Bot commands for approval workflows`,
  `are not yet implemented. Use the SPNET-ADMIN interface for full approval management.`,
  ``,
  `*9. Investigations*`,
  `• /investigations — List all investigations (filter by status: ACTIVE, COMPLETED)`,
  `Investigations support evidence collection (messages, documents, data),`,
  `status transitions (ACTIVE → COMPLETED), and full audit trails.`,
  `Detailed investigation views, evidence, timelines, assignment, and closure`,
  `are available via the API.`,
  ``,
  `*10. Emergency Actions*`,
  `• /health — Immediate system health check`,
  `• /system — Full system status including services and alerts`,
  `• /stats — System performance statistics and latency`,
  `• /syncstatus — Sync pipeline health and DLQ count`,
  `• /incident — List current active incidents`,
  `• /resolveincident <id> — Resolve an active incident`,
  `• /lockdown <resource> — Trigger security lockdown (admin only)`,
  `• /liftlockdown <resource> — Lift a security lockdown (admin only)`,
  `• /deeplinks — View active deep links`,
  `• /services — Monitoring service status`,
  `In an emergency, start with /health → /system → /incident to assess.`,
  `Use /syncstatus to verify sync pipeline health.`,
  ``,
  `*11. Troubleshooting*`,
  `• *Command not found* — Run /commands for the full command list`,
  `• *Access denied* — Use /accessaudit <staffId> to check current permissions`,
  `• *User not found* — Use /staff to list all staff members and verify IDs`,
  `• *Sync failure* — Use /syncstatus to check the sync pipeline health`,
  `• *System issues* — Use /health then /system for diagnostics`,
  `• *Audit trail* — Use /audit, /audituser <userId>, /auditstaff <staffId>`,
  `• *Dashboard issues* — Use /staffdashboard or /activedashboard`,
  `• *Telegram bots* — If bot is not responding, check BOT_TOKEN is set`,
  `• *Database issues* — Check database connectivity and migrations`,
  `For persistent issues, check audit logs or contact OWNER/SUPER_ADMINISTRATOR.`,
].join('\n')

const COMMANDS_TEXT = [
  `*SPNETGRAM Admin Bot — All Commands*\n`,
  `*General (public):*`,
  `/help, /start`,
  ``,
  `*Staff Management:*`,
  `/staff, /departments`,
  `/grantrole <staffId> <roleName>, /revokerole <staffId> <roleName>`,
  `/grantpermission <staffId> <resource> <action>, /revokepermission <staffId> <resource> <action>`,
  `/temporaryaccess <staffId> <resource> <action> <hours>, /accessaudit <staffId>`,
  ``,
  `*Moderation:*`,
  `/warn <user> <reason>, /mute <user> <minutes> <reason>`,
  `/ban <user> <reason>, /unban <user> <reason>, /unmute <user> <reason>`,
  ``,
  `*Premium:*`,
  `/premium, /plans, /requestpremium <userId> <planId>, /mypremium`,
  ``,
  `*Emergency:*`,
  `/lockdown <reason>, /liftlockdown`,
  ``,
  `*Cases:*`,
  `/cases [status]`,
  ``,
  `*Tickets:*`,
  `/tickets [status], /ticketsummary`,
  ``,
  `*Investigations:*`,
  `/investigations [status]`,
  ``,
  `*Security:*`,
  `/security, /securitylogs, /risk, /fraud, /sessionaudit`,
  ``,
  `*Monitoring:*`,
  `/services, /health, /system, /stats, /latency`,
  ``,
  `*Incidents:*`,
  `/incident, /incidentstatus <id>, /resolveincident <id>, /incidenttimeline <id>`,
  ``,
  `*AI Operations:*`,
  `/summarize, /ticketsummary, /recommendation`,
  ``,
  `*Analytics:*`,
  `/executivedashboard, /companyreport`,
  ``,
  `*Audit:*`,
  `/audit, /audituser <userId>, /auditstaff <staffId>`,
  ``,
  `*Dashboards:*`,
  `/staffdashboard, /activedashboard`,
  ``,
  `*Sync:*`,
  `/syncstatus`,
  ``,
  `*Deep Links:*`,
  `/deeplinks`,
  ``,
  `*Governance:*`,
  `/grantrole, /revokerole, /grantpermission, /revokepermission, /temporaryaccess, /accessaudit`,
  ``,
  `*Help:*`,
  `/guide, /commands, /examples`,
].join('\n')

const EXAMPLES_TEXT = [
  `*SPNETGRAM Admin Bot — Usage Examples*\n`,
  `*Security:*`,
  `  /security — Security summary dashboard`,
  `  /securitylogs — Recent security events (24h)`,
  `  /risk — Risk analysis`,
  `  /fraud — Fraud pattern detection`,
  `  /sessionaudit — User login session history`,
  ``,
  `*Moderation:*`,
  `  /warn @user Spamming in chat`,
  `  /mute @user 30 Repeated violations`,
  `  /ban @user Permanent ban evasion`,
  `  /unban @user Appeal approved`,
  `  /unmute @user Behavior improved`,
  ``,
  `*Premium:*`,
  `  /premium — Overview of plans`,
  `  /plans — List available plans`,
  `  /requestpremium user-abc plan-pro — Grant Pro plan`,
  `  /mypremium — Your subscriptions`,
  ``,
  `*Emergency:*`,
  `  /lockdown Security breach detected`,
  `  /liftlockdown — Deactivate lockdown`,
  ``,
  `*Tickets:*`,
  `  /tickets — List all tickets`,
  `  /tickets OPEN — Filter by status`,
  `  /ticketsummary — Ticket statistics`,
  ``,
  `*Cases:*`,
  `  /cases — List all cases`,
  `  /cases ACTIVE — Filter by status`,
  ``,
  `*Staff Management:*`,
  `  /grantrole staff123 MANAGER`,
  `  /revokerole staff123 MANAGER`,
  `  /grantpermission staff123 USERS READ`,
  `  /temporaryaccess staff123 ECONOMY CREDIT 24`,
  `  /accessaudit staff123`,
  ``,
  `*Investigations:*`,
  `  /investigations — List all`,
  `  /investigations ACTIVE — Active only`,
  ``,
  `*Emergency:*`,
  `  /health — System health`,
  `  /system — Full status`,
  `  /syncstatus — Sync pipeline health`,
  `  /incidentstatus abc123 — Check incident`,
  `  /resolveincident abc123 — Resolve incident`,
  ``,
  `*Troubleshooting:*`,
  `  /accessaudit staff123 — Check permissions`,
  `  /audituser user123 — User audit trail`,
  `  /auditstaff staff123 — Staff audit trail`,
].join('\n')

export function registerGuideCommands(bot: Telegraf): void {
  bot.command('guide', async (ctx) => {
    try {
      await ctx.replyWithMarkdown(GUIDE_TEXT)
    } catch (err) {
      await ctx.reply(`Guide error: ${err instanceof Error ? err.message : 'Unknown'}`)
    }
  })

  bot.command('commands', async (ctx) => {
    try {
      await ctx.replyWithMarkdown(COMMANDS_TEXT)
    } catch (err) {
      await ctx.reply(`Commands error: ${err instanceof Error ? err.message : 'Unknown'}`)
    }
  })

  bot.command('examples', async (ctx) => {
    try {
      await ctx.replyWithMarkdown(EXAMPLES_TEXT)
    } catch (err) {
      await ctx.reply(`Examples error: ${err instanceof Error ? err.message : 'Unknown'}`)
    }
  })
}
